project:
  type: website
  execute-dir: project

execute:
  freeze: auto

website:
  title: "extendr"
  reader-mode: true
  repo-url: https://github.com/extendr/user-guide
  repo-actions: [edit, issue]
  repo-branch: main
  sidebar:
    contents: 
      - getting-started.qmd
      - hello-world.qmd
      - project-structure.qmd
      - conversion.qmd
    style: "docked"
    search: true
  navbar:
    left:
      - index.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



